name: SmartRustyConnectorModule
version: '${version}'
description: Smart RustyConnector Module
author: Funasitien
website: https://smart.democraft.fr
main: fr.democraft.rcs.NotAPlugin
api-version: '1.21'